// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdrxRVrd7_jDJxRneJSzY0Xh4BHjGVWaM',
    appId: '1:446650857393:web:2802281a43b23b7d26af90',
    messagingSenderId: '446650857393',
    projectId: 'suivi-de-module',
    authDomain: 'suivi-de-module.firebaseapp.com',
    databaseURL: 'https://suivi-de-module-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'suivi-de-module.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoax5K_GNjSQy2SbXB8rxe6PmeaLX_JUw',
    appId: '1:446650857393:android:51a0291df93b1c0e26af90',
    messagingSenderId: '446650857393',
    projectId: 'suivi-de-module',
    databaseURL: 'https://suivi-de-module-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'suivi-de-module.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4kXXLVNeOGESK67NsLxNdnQEmaV9gqWU',
    appId: '1:446650857393:ios:7f7731c9ee9b7ba926af90',
    messagingSenderId: '446650857393',
    projectId: 'suivi-de-module',
    databaseURL: 'https://suivi-de-module-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'suivi-de-module.appspot.com',
    iosClientId: '446650857393-kovhju3gqnfjouggjuqqusuoqg8ms753.apps.googleusercontent.com',
    iosBundleId: 'com.example.suiviDeModule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4kXXLVNeOGESK67NsLxNdnQEmaV9gqWU',
    appId: '1:446650857393:ios:3153fa93d26c042526af90',
    messagingSenderId: '446650857393',
    projectId: 'suivi-de-module',
    databaseURL: 'https://suivi-de-module-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'suivi-de-module.appspot.com',
    iosClientId: '446650857393-26d65emdj8f4gbg212ltkg2s4m3s29q2.apps.googleusercontent.com',
    iosBundleId: 'com.example.suiviDeModule.RunnerTests',
  );
}
